import { nanoid } from 'nanoid'

export const dataProducts = [
  {
    id: nanoid(),
    title: 'Peperomia Ginny',
    info: 'The flower of human being. It has meaningful of fact that the plant always grow whatever season and weather',
    img: 'product-01.jpg',
    price: 25,
    lables: ['Featured'],
  },
  {
    id: nanoid(),
    title: 'Bird’s Nest Fern',
    info: 'The flower of human being. It has meaningful of fact that the plant always grow whatever season and weather',
    img: 'product-02.jpg',
    price: 45,
    lables: ['Featured', 'New'],
  },
  {
    id: nanoid(),
    title: 'Large Majesty Palm',
    info: 'The flower of human being. It has meaningful of fact that the plant always grow whatever season and weather',
    img: 'product-03.jpg',
    price: 52,
    lables: ['Featured', '-20%'],
  },
  {
    id: nanoid(),
    title: 'Pet Friendly Plant',
    info: 'The flower of human being. It has meaningful of fact that the plant always grow whatever season and weather',
    img: 'product-04.jpg',
    price: 30,
    lables: ['Featured'],
  },
  {
    id: nanoid(),
    title: 'Scindapsus Global Green',
    info: 'The flower of human being. It has meaningful of fact that the plant always grow whatever season and weather',
    img: 'product-05.jpg',
    price: 35,
    lables: ['New'],
    isHeroImg1: true,
  },
  {
    id: nanoid(),
    title: 'Purple tulip',
    info: 'The flower of human being. It has meaningful of fact that the plant always grow whatever season and weather',
    img: 'product-06.jpg',
    price: 20,
    lables: ['Featured'],
    isMainHeroImg: true,
  },
  {
    id: nanoid(),
    title: 'Succulent cactus',
    info: 'The flower of human being. It has meaningful of fact that the plant always grow whatever season and weather',
    img: 'product-07.jpg',
    price: 57,
    lables: ['Popular'],
    isHeroImg2: true,
  },
  {
    id: nanoid(),
    title: 'Striped Tradescantia',
    info: 'The flower of human being. It has meaningful of fact that the plant always grow whatever season and weather',
    img: 'product-08.jpg',
    price: 48,
    lables: ['Featured'],
  },
  {
    id: nanoid(),
    title: 'Basil',
    info: 'The flower of human being. It has meaningful of fact that the plant always grow whatever season and weather',
    img: 'product-09.jpg',
    price: 15,
    lables: ['Popular'],
  },
  {
    id: nanoid(),
    title: 'Zamiokulkas',
    info: 'The flower of human being. It has meaningful of fact that the plant always grow whatever season and weather',
    img: 'product-10.jpg',
    price: 27,
    lables: ['Popular', '-20%'],
  },
  {
    id: nanoid(),
    title: 'Calathea orbifolia',
    info: 'The flower of human being. It has meaningful of fact that the plant always grow whatever season and weather',
    img: 'product-11.jpg',
    price: 41,
    lables: ['Popular', '-10%'],
  },
  {
    id: nanoid(),
    title: 'Succulent',
    info: 'The flower of human being. It has meaningful of fact that the plant always grow whatever season and weather',
    img: 'product-12.jpg',
    price: 34,
    lables: ['Popular'],
  },
  {
    id: nanoid(),
    title: 'Monstera',
    info: 'The flower of human being. It has meaningful of fact that the plant always grow whatever season and weather',
    img: 'product-13.jpg',
    price: 64,
    lables: ['New'],
  },
  {
    id: nanoid(),
    title: 'Philodendron scandens mycans',
    info: 'The flower of human being. It has meaningful of fact that the plant always grow whatever season and weather',
    img: 'product-14.jpg',
    price: 72,
    lables: ['New', 'Featured'],
  },
  {
    id: nanoid(),
    title: 'Cotyledon tomentosa',
    info: 'The flower of human being. It has meaningful of fact that the plant always grow whatever season and weather',
    img: 'product-15.jpg',
    price: 47,
    lables: ['New', '-10%'],
  },
  {
    id: nanoid(),
    title: 'Anthurium clarinervium',
    info: 'The flower of human being. It has meaningful of fact that the plant always grow whatever season and weather',
    img: 'product-16.jpg',
    price: 50,
    lables: ['New'],
  },
  {
    id: nanoid(),
    title: 'Harrys superstitions',
    info: 'The flower of human being. It has meaningful of fact that the plant always grow whatever season and weather',
    img: 'product-17.jpg',
    price: 35,
    lables: ['-10%'],
  },
  {
    id: nanoid(),
    title: 'Kalanchoe sexangularis',
    info: 'The flower of human being. It has meaningful of fact that the plant always grow whatever season and weather',
    img: 'product-18.jpg',
    price: 53,
    lables: [],
  },
  {
    id: nanoid(),
    title: 'Aloe',
    info: 'The flower of human being. It has meaningful of fact that the plant always grow whatever season and weather',
    img: 'product-19.jpg',
    price: 29,
    lables: ['-30%'],
  },
  {
    id: nanoid(),
    title: 'Hanging planters',
    info: 'The flower of human being. It has meaningful of fact that the plant always grow whatever season and weather',
    img: 'product-22.jpg',
    price: 7.2,
    lables: [],
    plantStand: true,
  },
  {
    id: nanoid(),
    title: 'Hanging planters',
    info: 'The flower of human being. It has meaningful of fact that the plant always grow whatever season and weather',
    img: 'product-23.jpg',
    price: 8,
    lables: ['New'],
    plantStand: true,
  },
  {
    id: nanoid(),
    title: 'S Hooks',
    info: 'The flower of human being. It has meaningful of fact that the plant always grow whatever season and weather',
    img: 'product-24.jpg',
    price: 1.1,
    lables: [],
    plantStand: true,
  },
  {
    id: nanoid(),
    title: 'Porte Plantes',
    info: 'The flower of human being. It has meaningful of fact that the plant always grow whatever season and weather',
    img: 'product-25.jpg',
    price: 28,
    lables: [],
    plantStand: true,
  },
  {
    id: nanoid(),
    title: 'Flower stand 1',
    info: 'The flower of human being. It has meaningful of fact that the plant always grow whatever season and weather',
    img: 'product-26.webp',
    price: 20,
    lables: [],
    plantStand: true,
  },
  {
    id: nanoid(),
    title: 'Flower stand 2',
    info: 'The flower of human being. It has meaningful of fact that the plant always grow whatever season and weather',
    img: 'product-27.webp',
    price: 20,
    lables: ['-10%'],
    plantStand: true,
  },
  // {
  //   title: 'Flower stand 3',
  //   info: 'The flower of human being. It has meaningful of fact that the plant always grow whatever season and weather',
  //   img: 'product-28.webp',
  //   price: 24,
  //   lables: [],
  //   plantStand: true,
  // },
  {
    id: nanoid(),
    title: 'Flower stand 4',
    info: 'The flower of human being. It has meaningful of fact that the plant always grow whatever season and weather',
    img: 'product-29.webp',
    price: 10,
    lables: ['New'],
    plantStand: true,
  },
  {
    id: nanoid(),
    title: 'Flower stand 5',
    info: 'The flower of human being. It has meaningful of fact that the plant always grow whatever season and weather',
    img: 'product-30.webp',
    price: 17,
    lables: [],
    plantStand: true,
  },
  {
    id: nanoid(),
    title: 'Pot with Laura mint',
    info: 'The flower of human being. It has meaningful of fact that the plant always grow whatever season and weather',
    img: 'product-31.webp',
    price: 1.3,
    lables: [],
    plantStand: true,
    color: 'mint',
  },
  {
    id: nanoid(),
    title: 'Pot with Laura anthracite',
    info: 'The flower of human being. It has meaningful of fact that the plant always grow whatever season and weather',
    img: 'product-33.webp',
    price: 1.3,
    lables: [],
    plantStand: true,
    color: 'black',
  },
  {
    id: nanoid(),
    title: 'Pot with Laura white',
    info: 'The flower of human being. It has meaningful of fact that the plant always grow whatever season and weather',
    img: 'product-34.webp',
    price: 1.3,
    lables: [],
    plantStand: true,
    color: 'white',
  },
  {
    id: nanoid(),
    title: 'Pot with Laura beige',
    info: 'The flower of human being. It has meaningful of fact that the plant always grow whatever season and weather',
    img: 'product-32.webp',
    price: 1.3,
    lables: [],
    plantStand: true,
    color: 'beige',
  },
]

export const dataArrivals = [
  {
    title: 'Pelargonium',
    img: 'new-arrivals-01.jpg',
  },
  {
    title: 'The Primrose',
    img: 'new-arrivals-02.jpg',
  },
  {
    title: 'Bougainvillea Glabra',
    img: 'new-arrivals-03.jpg',
  },
  {
    title: 'Ampelnaya begonia',
    img: 'new-arrivals-04.jpg',
  },
  {
    title: 'Blue Lily',
    img: 'new-arrivals-06.jpg',
  },
  {
    title: 'Pineapple',
    img: 'new-arrivals-07.jpg',
  },
  {
    title: 'Portulaca umbraticola',
    img: 'new-arrivals-08.jpg',
  },
  {
    title: 'Sempervivum caucasicum',
    img: 'new-arrivals-09.jpg',
  },
]
